name: GH-Pages CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    # Depends on repo write scope token in secrets (GH_TOKEN)
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Setup GIT token
        uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: npm install, deploy
        run: |
          npm ci
          npm run deploy
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
