name: GH-Pages CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install, deploy
        run: |
          npm ci
          npm run deploy
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
